theme: jekyll-theme-leap-day
title: Michael L'Estrange
description: Unity Game Developer & Programmer
github:
  profile_url: https://github.com/miclede/
  home_url: https://miclede.github.io/portfolio/
  resume_url: https://raw.githubusercontent.com/miclede/portfolio/gh-pages/assets/MichaelLestrangeResume.pdf
  linkedin_url: https://www.linkedin.com/in/michael-l-estrange-67598b229/
  gamejam_url: https://github.com/miclede/Unscuffed-GameJam/releases
  zip_url: https://github.com/miclede/Unscuffed-GameJam/releases/download/v1.3b/Unscuffed.zip
