theme: jekyll-theme-leap-day
title: Michael L'Estrange
description: Unity Gamedev Portfolio
github:
  profile_url: https://github.com/miclede/
  home_url: https://miclede.github.io/portfolio/
  resume_url: https://miclede.github.io/portfolio/resume
  linkedin_url: https://miclede.github.io/portfolio/
